# Greath North Run data processing

In [2]:
import os

import numpy as np
import pandas as pd
import matplotlib.pyplot as mplt

In [26]:
raw_df = pd.read_excel("/home/petr/ow_challenge_gnr/2024 Data Challenge Raw Data.xlsx")
raw_df.shape

(14614, 17)

## Row descriptions
|Variable |	Definition |
| :-: | :- |
| club |	The club the runner is a part of 
|position |	The position the runner finished in 
|time |	The time the runner took to finish the race
|id |	The runners id
|gender	| The runners gender
|trained_10_week |	The average number of times per week the runner trained 10 or more weeks ago
|trained_im	| The average number of times per week the runner trained less than e weeks ago
|has_trainer |	Whether the runner has a trainer or not
|cadence |	The average number of steps the runner took per minute
|age |	The age of the runner
|bmi |	The bmi of the runner
|n_marathons_run |	The number of marathons the runner has run before the race
|bib_colour |	The runners bib colour
|VO2_max |	The VO2 max of the runner
|heart_rate	| The resting heart rate of the runner
|shoe_size	| The runner's shoe size


NOTE:  
*Bib colours have meaning:  
Orange:

In [18]:
raw_df.head()

#figure out unnamed column name- external sources?
#fix club names for all the records, fill up until you find text

,Unnamed: 0,club,position,time,id,gender,trained_10_week,trained_im,has_trainer,cadence,age,bmi,n_marathons_run,bib_colour,VO2_max,heart_rate,shoe_size
0,7448,NaN,14589,03:45:46,7426,female,0.789725,0.789725,0,163,36.0,999.00,0.0,green,12.718323,103.67,6
1,5363,NaN,14588,03:26:28,5345,female,1.670838,1.670838,0,157,30.0,19.05,0.0,green,12.718323,99.33,5
2,11420,NaN,14587,03:26:22,11387,female,1.917839,1.917839,0,165,38.0,21.13,0.0,green,13.460000,98.43,6
3,9408,Gump's training,14586,03:21:13,9384,male,0.000000,0.000000,0,154,38.0,18.86,0.0,green,20.010000,100.91,7
4,6604,NaN,14585,03:20:19,6585,female,0.000000,0.710092,0,166,43.0,19.75,0.0,green,12.718323,102.45,6

In [19]:
#no of missing values in each column 
raw_df.isnull().sum()

#autofill club information for all the other missing rows, boundaries to be defined from the excel spreadsheet 
#strategy for rows with missing time, impute/discard?
#

Unnamed: 0             0
club               11425
position               0
time                  47
id                     0
gender                 0
trained_10_week       74
trained_im           151
has_trainer            0
cadence                0
age                   51
bmi                    0
n_marathons_run       37
bib_colour             0
VO2_max              572
heart_rate           550
shoe_size              0
dtype: int64

In [ ]:
raw_df.describe()

#trained 10 weeks, verify -999
#max BMI 999, fix that
#fix -9 in min for n_marathons_run
#fix max for n_marathons_run. is it normal for someone to run 1mil marathons? anomaly- discard

,Unnamed: 0,position,id,trained_10_week,trained_im,has_trainer,cadence,age,bmi,n_marathons_run,VO2_max,heart_rate,shoe_size
count,14614.000000,14614.000000,14614.000000,14540.000000,14463.000000,14614.000000,14614.000000,14563.000000,14614.000000,14577.000000,14042.000000,14064.000000,14614.000000
mean,7328.758656,7280.848159,7306.500000,-3.083608,-8.237465,0.078692,159.093540,36.102383,60.647316,3084.041984,44.585019,81.290607,7.656631
std,4231.313944,4219.205169,4218.842752,75.482450,106.119666,0.269266,32.010322,9.891467,189.231907,54865.742122,19.961066,10.775136,3.041907
min,0.000000,1.000000,0.000000,-999.000000,-999.000000,0.000000,1.000000,18.000000,15.050000,-9.000000,10.010000,58.680000,3.000000
25%,3665.250000,3627.250000,3653.250000,1.183613,2.008240,0.000000,161.000000,30.000000,21.120000,3.000000,28.260000,72.207500,5.000000
50%,7328.500000,7280.500000,7306.500000,2.745488,3.251724,0.000000,165.000000,36.000000,22.610000,6.000000,43.280000,80.740000,7.000000
75%,10992.750000,10933.750000,10959.750000,4.023773,4.332161,0.000000,169.000000,42.000000,24.180000,11.000000,60.827500,89.952500,10.000000
max,14660.000000,14589.000000,14613.000000,6.919653,6.919653,1.000000,189.000000,83.000000,999.000000,1000000.000000,95.850000,114.830000,13.000000

In [24]:

print( raw_df.bib_colour.value_counts())

bib_colour
green     5785
blue      4397
yellow    2925
red       1507
Name: count, dtype: int64

In [ ]:
# Cleaning steps
# remove non existant: position, id, final time
# trained_10_week & trained_im: replace negative with zero
# has_trainer: one hot (already one hot)
# bib colour: one hot
# bmi: remove outliers
# n_runs: remove negative and outliers
# sex: one hot
#